apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    layer: webservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      #During this Pod's initialization, check that myconfig service is up and running before starting this pod
      - name: check-message-bus-ready
        image: busybox:latest
        command: ['sh', '-c', 'until nc -vz phpfpm 9000; do echo "Waiting for phpfpm service"; sleep 2; done;']
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html/
          name: contents
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: contents
        hostPath:
          path: /files
          type: Directory
      - name: nginx-config
        configMap:
          name: nginx
